apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dind
  name: dind
spec:
  containers:
  - image: docker.io/coldwater/dind:master
    name: dind
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  hostPID: true
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker-socket
